In [1]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import tensorflow as tf

In [5]:
sess = tf.Session()

In [8]:
my_data = [
    [0, 1,],
    [2, 3,],
    [4, 5,],
    [6, 7,],
]
slices = tf.data.Dataset.from_tensor_slices(my_data)
next_item = slices.make_one_shot_iterator().get_next()

In [9]:
while True:
  try:
    print(sess.run(next_item))
  except tf.errors.OutOfRangeError:
    break

[0 1]
[2 3]
[4 5]
[6 7]


In [13]:
r = tf.random_normal([10,3])
dataset = tf.data.Dataset.from_tensor_slices(r)
iterator = dataset.make_initializable_iterator()
next_row = iterator.get_next()

sess.run(iterator.initializer)
while True:
  try:
    print(sess.run(next_row))
  except tf.errors.OutOfRangeError:
    break

[ 1.1836     -0.92454654  1.1309423 ]
[ 1.0880215  -0.79406744 -1.1601129 ]
[-0.28155568  0.81876904 -1.0433365 ]
[-0.8199923  0.2502016  1.2425392]
[ 2.5896118   1.4418368  -0.61610603]
[1.195764   0.08506685 2.4161427 ]
[-0.1687492 -1.5672297  0.841155 ]
[ 0.73468274 -0.30991885 -0.1340497 ]
[-0.6971009  -0.09129202 -0.2834634 ]
[-0.5084083  -1.4442104  -0.17629611]


In [20]:
x = tf.placeholder(tf.float32, shape=[None, 3])
linear_model = tf.layers.Dense(units=1)
y = linear_model(x)
y,linear_model

(<tf.Tensor 'dense_3/BiasAdd:0' shape=(?, 1) dtype=float32>,
 <tensorflow.python.layers.core.Dense at 0x1294560f0>)

In [21]:
init = tf.global_variables_initializer()
print(sess.run(init))

None


In [22]:
features = {
    'sales' : [[5], [10], [8], [9]],
    'department': ['sports', 'sports', 'gardening', 'gardening']}

department_column = tf.feature_column.categorical_column_with_vocabulary_list(
        'department', ['sports', 'gardening'])
department_column = tf.feature_column.indicator_column(department_column)

columns = [
    tf.feature_column.numeric_column('sales'),
    department_column
]

inputs = tf.feature_column.input_layer(features, columns)


Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
Instructions for updating:
Use tf.cast instead.
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please 

In [23]:
var_init = tf.global_variables_initializer()
table_init = tf.tables_initializer()
sess = tf.Session()
sess.run((var_init, table_init))

(None, None)

In [24]:
print(sess.run(inputs))

[[ 1.  0.  5.]
 [ 1.  0. 10.]
 [ 0.  1.  8.]
 [ 0.  1.  9.]]


# Simple Regression

In [58]:
x = tf.constant([[1], [2], [3], [4]], dtype=tf.float32)
# y_true = tf.constant([[0], [0], [0], [0]], dtype=tf.float32)
y_true = tf.constant([[0], [-1], [-2], [-3]], dtype=tf.float32)

In [59]:
linear_model = tf.layers.Dense(units=1)

y_pred = linear_model(x)

In [60]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

print(sess.run(y_pred))

[[0.6089865]
 [1.217973 ]
 [1.8269595]
 [2.435946 ]]


In [61]:
loss = tf.losses.mean_squared_error(labels=y_true, predictions=y_pred)

print(sess.run(loss))

2.7814841


In [68]:
optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(-loss)

In [71]:
for i in range(100):
  _, loss_value = sess.run((train, loss))
  print(loss_value)

0.0069321874
0.008318247
0.010199196
0.012754094
0.016226798
0.020949438
0.027374316
0.036117442
0.048017755
0.064217806
0.08627364
0.11630447
0.15719637
0.21288
0.28870854
0.39197236
0.5326003
0.72411454
0.98493123
1.3401308
1.8238705
2.4826698
3.3798835
4.6017933
6.2659097
8.532267
11.618817
15.822395
21.547253
29.343945
39.96228
54.42341
74.11806
100.940254
137.4695
187.21878
254.97246
347.24646
472.91467
644.06256
877.1494
1194.5912
1626.9161
2215.701
3017.5688
4109.6353
5596.924
7622.467
10381.061
14137.999
19254.586
26222.88
35713.023
48637.688
66239.83
90212.234
122860.33
167323.86
227878.9
310349.06
422665.4
575629.4
783951.5
1067666.0
1454057.8
1980286.1
2696958.2
3672996.0
5002264.5
6812600.0
9278102.0
12635877.0
17208840.0
23436776.0
31918622.0
43470070.0
59202024.0
80627430.0
109806770.0
149546200.0
203667440.0
277375360.0
377758370.0
514470370.0
700658900.0
954229570.0
1299568300.0
1769886200.0
2410413600.0
3282750200.0
4470787600.0
6088781000.0
8292330500.0
11293350000.0


In [72]:

print(sess.run(y_pred))

[[137545.27]
 [240181.8 ]
 [342818.3 ]
 [445454.88]]


In [65]:
12.3 - 4.85j

(12.3-4.85j)